код с урока вылетает ошибка: в fragment_coordinator.xml
android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class com.google.android.material.appbar.CollapsingToolbarLayout
    Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.google.android.material.appbar.CollapsingToolbarLayout
    Caused by: java.lang.reflect.InvocationTargetException